<section class="gp" id="gpRoot" aria-label="Plantation">
  <header class="gp-heading"><div><span class="gp-kicker">GREENSTAND / BOTANICAL CLUB</span><h1>Ta petite jungle.</h1><p>La collection grandit. Les recettes évoluent. Ta serre aussi.</p></div><div class="gp-balance"><span>POINTS DE SERRE</span><b id="gpCredits">—</b><small>Gagnés à chaque récolte</small></div></header>
  <div class="gp-message" id="gpMessage" role="status" aria-live="polite">Ouverture de ta serre…</div>
  <div class="gp-layout">
    <div class="gp-workspace">
      <div class="gp-scene" id="gpScene"><div class="gp-scene-label"><span class="gp-live"></span> LA SERRE <span id="gpSceneCount"></span></div><div id="gpCanvas"></div><div class="gp-scene-controls"><button type="button" id="gpInspect">Voir le bud</button><button type="button" id="gpRotate">Rotation auto</button><button type="button" id="gpLight" aria-pressed="true">Lampe allumée</button><button type="button" id="gpSound" aria-pressed="true">Son activé</button><button type="button" id="gpPhoto" title="Enregistrer une photo de la serre">Photo</button></div><div class="gp-toasts" id="gpToasts" aria-live="polite" aria-atomic="false"></div><p class="gp-scene-hint">Glisse pour tourner · molette ou pincement pour zoomer · raccourcis <kbd>1</kbd>-<kbd>6</kbd> <kbd>T</kbd> <kbd>S</kbd> <kbd>A</kbd> <kbd>F</kbd> <kbd>R</kbd></p></div>
      <div class="gp-pot-tabs" id="gpPots" aria-label="Choisir un pot"></div>
      <div class="gp-stats"><div><b id="gpScore">0</b><span>score plantation · <a href="classement.php">classement</a></span></div><div><b id="gpHarvestTotal">0</b><span>récoltes</span></div><div><b id="gpDiscovered">0 / 500</b><span>hybrides découverts</span></div><div><b id="gpBudTotal">0</b><span>buds en collection</span></div></div>
    </div>
    <aside class="gp-care">
      <div class="gp-care-title"><span class="gp-kicker" id="gpPotNumber">POT 01</span><span class="gp-stage" id="gpStage">En attente</span></div>
      <h2 id="gpPlantName">Un nouveau départ.</h2><p id="gpNext" class="gp-muted">Choisis un pot pour commencer.</p>
      <div class="gp-progress"><span id="gpProgress"></span></div><div class="gp-timing"><span id="gpTime">—</span><span id="gpQuality"></span></div>
      <label class="gp-label" for="gpSeedSelect">La graine à semer</label><select id="gpSeedSelect"></select>
      <div class="gp-tools" id="gpTools">
        <button type="button" data-action="soil"><span class="gp-tool-mark">01</span><span>Terreau<small>Préparer le pot</small></span><i id="gpSoilCount"></i></button>
        <button type="button" data-action="plant"><span class="gp-tool-mark">02</span><span>Semer<small>Une graine, une plante</small></span></button>
        <button type="button" data-action="water"><span class="gp-tool-mark">03</span><span>Arroser<small>Lancer la pousse</small></span><i id="gpWaterCount"></i></button>
        <button type="button" data-action="feed"><span class="gp-tool-mark">✦</span><span>Soin bonus<small>+1 bud à la récolte</small></span><i id="gpFeedCount"></i></button>
      </div>
      <button class="gp-primary gp-harvest" id="gpHarvest" type="button">✂ Récolter aux ciseaux</button>
      <button class="gp-secondary gp-harvest-all" id="gpHarvestAll" type="button" hidden>✂ Tout récolter</button>
      <p class="gp-fine">Kit inclus : pots, pelle, arrosoir, lampe, ciseaux et bocaux. Ta plante continue de pousser pendant ton absence.</p>
    </aside>
  </div>
  <nav class="gp-section-tabs" aria-label="Atelier"><button type="button" class="active" data-tab="seeds" aria-pressed="true">Grainothèque <span>50</span></button><button type="button" data-tab="lab" aria-pressed="false">Laboratoire <span>500</span></button><button type="button" data-tab="collection" aria-pressed="false">Collection</button><button type="button" data-tab="supplies" aria-pressed="false">Matériel</button></nav>
<div class="gp-filter"><label for="gpSearch">Trouver une variété</label><input id="gpSearch" type="search" placeholder="Nom ou parent…" autocomplete="off"><span>50 fondatrices · 500 recettes</span><label class="gp-check" for="gpOnlyFound"><input type="checkbox" id="gpOnlyFound"> Uniquement mes découvertes</label></div>
<div class="gp-rarity-bar" role="group" aria-label="Filtrer par rareté"><button type="button" class="active" data-rarity="" aria-pressed="true">Toutes</button><button type="button" data-rarity="0" aria-pressed="false">Communes</button><button type="button" data-rarity="1" aria-pressed="false">Rares</button><button type="button" data-rarity="2" aria-pressed="false">Épiques</button><button type="button" data-rarity="3" aria-pressed="false">Légendaires</button><button type="button" data-rarity="4" aria-pressed="false">Mythiques</button><span id="gpFilterCount"></span></div>
  <section id="gp-seeds" class="gp-section"><div class="gp-section-heading"><div><span class="gp-kicker">LES FONDATRICES</span><h2>Cinquante origines. Ton prochain hybride.</h2></div><p>Deux graines de chaque fondatrice commune offertes au départ.<br>Les fondatrices rares s’achètent, chaque récolte redonne deux graines.</p></div><div id="gpSeedGrid" class="gp-card-grid"></div></section>
  <section id="gp-lab" class="gp-section" hidden><div class="gp-section-heading"><div><span class="gp-kicker">LE LABORATOIRE</span><h2>Une rencontre. Une nouvelle variété.</h2></div><p>Récolte les deux parents, puis associe leurs graines.<br>500 recettes réparties en cinq raretés : plus c’est rare, plus il faut de maîtrise.</p></div><div class="gp-lab-bench"><div><label for="gpParentA">Parent A</label><select id="gpParentA"></select></div><span class="gp-cross-symbol">×</span><div><label for="gpParentB">Parent B</label><select id="gpParentB"></select></div><span class="gp-cross-symbol">→</span><div class="gp-hybrid-result" id="gpHybridResult"></div><button type="button" class="gp-primary" id="gpCross">Créer la graine · 60 pts</button></div><p id="gpLabHint" class="gp-muted"></p><div id="gpHybridGrid" class="gp-card-grid"></div></section>
  <section id="gp-collection" class="gp-section" hidden><div class="gp-section-heading"><div><span class="gp-kicker">LE CABINET BOTANIQUE</span><h2>Tes plus belles récoltes.</h2></div><p>Tourne les plantes dans la serre et retrouve ici<br>chaque bud de ta collection.</p></div><div id="gpCollectionGrid" class="gp-card-grid"></div><h3 class="gp-journal-title">Journal de serre</h3><ol id="gpHistory" class="gp-history"></ol></section>
  <section id="gp-supplies" class="gp-section" hidden><div class="gp-section-heading"><div><span class="gp-kicker">L’ÉTABLI</span><h2>Tout à portée de main.</h2></div><p>L’eau se recharge gratuitement.<br>Les points de serre restent propres à cet atelier.</p></div><div class="gp-supplies"><article><span class="gp-supply-symbol">▱</span><h3>Terreau</h3><p>5 préparations de pot.</p><button type="button" data-buy="soil">5 sacs · 15 pts</button></article><article><span class="gp-supply-symbol">◈</span><h3>Réserve d’eau</h3><p>Remplis les 6 doses de ton arrosoir.</p><button type="button" id="gpRefill">Remplir gratuitement</button></article><article><span class="gp-supply-symbol">✦</span><h3>Soins bonus</h3><p>5 jetons pour des récoltes étoilées.</p><button type="button" data-buy="feed">5 soins · 20 pts</button></article><article><span class="gp-supply-symbol">⊞</span><h3>Agrandir la serre</h3><p>Jusqu’à six pots simultanément.</p><button type="button" id="gpUnlockPot">Débloquer un pot</button></article></div><div class="gp-supplies gp-accessories"><article><span class="gp-supply-symbol">✺</span><h3>Ventilateur rétro</h3><p>Un nouvel objet animé sur l’établi.</p><button type="button" data-accessory="fan">Installer · 120 pts</button></article><article><span class="gp-supply-symbol">♧</span><h3>Brumisateur</h3><p>Une brume d’ambiance dans ta serre.</p><button type="button" data-accessory="humidifier">Installer · 140 pts</button></article><article><span class="gp-supply-symbol">⌕</span><h3>Loupe botanique</h3><p>Un accessoire de collection pour ton établi.</p><button type="button" data-accessory="loupe">Installer · 100 pts</button></article></div><p class="gp-fine">Accessoires décoratifs : aucun avantage au classement. La vue détaillée des buds est accessible à tous.</p></section>
  <footer class="gp-footer">BOTANICAL CLUB · Culture et croisements de jeu imaginaires · 50 fondatrices + 500 hybrides</footer>
</section>
